### PR TITLE
Help maintaining https://github.com/OCA/l10n-italy

### PR DESCRIPTION
**Pull request by MarcoCalcagni**
@OCA/local-italy-maintainers let me know what you think 😄. Grazie

### CODE REVIEW

**Review by SirAionTech — APPROVED** [review]

**Review by eLBati — APPROVED** [review]

**Comment by simahawk** [comment]
Ci devo pensare... :smile:

**Review by MaurizioConte — APPROVED** [review]

**Comment by sergiocorato** [comment]
:clap:

**Comment by sergiocorato** [comment]
> 👏
@simahawk anyway, I think next time it should be better to wait some days to let other members to join the discussion on the PR, as 45 minutes seems a very short time to have a normal visibility.

**Comment by TheMule71** [comment]
> > 👏
> 
> @simahawk anyway, I think next time it should be better to wait some days to let other members to join the discussion on the PR, as 45 minutes seems a very short time to have a normal visibility.

I second this.

**Comment by simahawk** [comment]
> > 👏
> 
> @simahawk anyway, I think next time it should be better to wait some days to let other members to join the discussion on the PR, as 45 minutes seems a very short time to have a normal visibility.

@sergiocorato fine for me. I gave for granted there was already a discussion beforehand. Do you want me to rollback?

**Comment by sergiocorato** [comment]
> > > 👏
> > 
> > @simahawk anyway, I think next time it should be better to wait some days to let other members to join the discussion on the PR, as 45 minutes seems a very short time to have a normal visibility.
> 
> @sergiocorato fine for me. I gave for granted there was already a discussion beforehand. Do you want me to rollback?

Good. No it's ok, thanks.

**Pull request merged**
