### PR TITLE
Help maintaining https://github.com/OCA/l10n-italy

### PR DESCRIPTION
**Pull request by SirAionTech**
@OCA/local-italy-maintainers let me know what you think :smile:

### CODE REVIEW

**Review by aleuffre — APPROVED** [review]

**Review by francesco-ooops — APPROVED** [review]

**Review by OpenCode — APPROVED** [review]

**Review by primes2h — APPROVED** [review]

**Comment by francesco-ooops** [comment]
@etobella @pedrobaeza just to know, what are the requirements to merge a maintainership candidature?

**Comment by SirAionTech** [comment]
> Thanks, the page itself doesn't seem to provide clear info regarding my questions, especially since the line "If you are not yet a PSC member but are interested in joining one then please [start here](https://odoo-community.org/about/psc-guide)." is a recursive link

I agree that the documentation should be updated, see https://github.com/OCA/repo-maintainer-conf/issues/21.

**Review by MarcoCalcagni — APPROVED** [review]
👍

**Review by sergiocorato — APPROVED** [review]

**Review by etobella — APPROVED** [review]
5 of 9 PSC members approved it. So it seems legit to me

**Pull request merged**
