### PR TITLE
[ADD] alexey-pelykh as member of crm

### PR DESCRIPTION
**Pull request by alexey-pelykh**

### CODE REVIEW

**Comment by alexey-pelykh** [comment]
@rousseldenis here you go:
https://github.com/OCA/sale-workflow/pull/2991
https://github.com/OCA/sale-workflow/pull/2992
https://github.com/OCA/sale-workflow/pull/2994
https://github.com/OCA/sale-workflow/pull/2996
https://github.com/OCA/sale-workflow/pull/2997

**Comment by rousseldenis** [comment]
I would say your contribution is currently too limited to apply as it covers just one module.

@OCA/crm-sales-marketing-maintainers

**Comment by alexey-pelykh** [comment]
One module so far with mistakes in migration since at least v14 if not earlier 🤷‍♂️

**Comment by pedrobaeza** [comment]
You can convert into maintainer of such module and have the same merge rights as being a PSC in that module.

**Comment by alexey-pelykh** [comment]
@pedrobaeza as you might have guessed, that specific module just happens to be the first one of a few that I'm interested in, and I'm already extremely happy about response time :D obviously, nothing surprising or new :)

**Comment by pedrobaeza** [comment]
Yeah, but this PSC is very wide for giving full access. You can review other PRs and ask in exchange that other review yours.

**Comment by alexey-pelykh** [comment]
Can't argue with that, indeed withs PSC team covers too much repos

**Comment by alexey-pelykh** [comment]
https://github.com/OCA/sale-workflow/pull/3010 then and I'll close off this for now yet it seems that it's also good to split the CRM PSC team into more than one.

**Comment by rousseldenis** [comment]
> [OCA/sale-workflow#3010](https://github.com/OCA/sale-workflow/pull/3010) then and I'll close off this for now yet it seems that it's also good to split the CRM PSC team into more than one.

Maybe, but you found the solution by adopting the module :smiley:

**Pull request closed without merging**
