### PR TITLE
[IMP] update default branch in operating-unit repo

### PR DESCRIPTION
**Pull request by AaronHForgeFlow**
Based on the newest branch with some modules in it

### CODE REVIEW

**Review by aleuffre — APPROVED** [review]

**Comment by simahawk** [comment]
build issue is unrelated, checking

**Comment by simahawk** [comment]
@AaronHForgeFlow pls rebase

**Comment by AaronHForgeFlow** [comment]
Rebased. Thanks

**Review by etobella — APPROVED** [review]

**Pull request merged**
