### PR TITLE
Fix some PSC and missing report-print-send

### LINKED ISSUE #2: Wrong PSC conf for some repos
Many repos seems to be tied to core maintainers only.
It seems it happened only when multiple repos are in the same file.
TODO: check for the bug in the bootstrap data script and update the conf here.

Examples:
1. https://github.com/OCA/repo-maintainer-conf/blob/master/conf/repo/account.yml
2. https://github.com/OCA/repo-maintainer-conf/blob/master/conf/repo/bank.yml
3. https://github.com/OCA/repo-maintainer-conf/blob/master/conf/repo/connector.yml

### PR DESCRIPTION
**Pull request by simahawk**
Fix some PSC and missing report-print-send

Fixes #2

Meanwhile, branch 17.0 has been created for some repos.

### CODE REVIEW

**Comment by etobella** [comment]
The problem comes from not setting the force and push to the repo. For that, we need to do the following:

1. https://github.com/OCA/repo-maintainer/pull/16
2. Modify the action so it commits and pushes the modified file. We can also modify the repo-maintainer to push it, but that might be dirty :thinking:

**Comment by etobella** [comment]
We can use this: https://github.com/stefanzweifel/git-auto-commit-action

But I would like to obtain some comments first:

@simahawk @sbidoul

**Comment by etobella** [comment]
Oops, Yes, we need to merge this changes, as the information is not correctly processed. Anyway, i think we need to apply the proposed changes if possible.

**Comment by simahawk** [comment]
@etobella I'm not sure to understand how this is related to this issue. Here we just had wrong conf from bootstrap_data. And I fixed it. For the conf to be correct we just need to merge this PR.

**Comment by simahawk** [comment]
The problem w/ the build is another story https://github.com/OCA/repo-maintainer-conf/issues/1

**Comment by etobella** [comment]
I know, I misplaced the comment. Here we can find an issue we need to solve by merging it.

However, you applied a change on repo-maintainer that would allow us to use less connections by keeping the checksum of files. My proposal was related to that.

**Comment by simahawk** [comment]
> I know, I misplaced the comment. Here we can find an issue we need to solve by merging it.
> 
> However, you applied a change on repo-maintainer that would allow us to use less connections by keeping the checksum of files. My proposal was related to that.

Ahh, I see now. We "just" forgot to add an action to update the checksum of the files :bulb:

**Comment by simahawk** [comment]
I created https://github.com/OCA/repo-maintainer-conf/issues/4 to follow up

**Pull request merged**
